/**
 * generate_search_index.js
 *
 * Extracts search-relevant metadata (room lists, faculty profiles, labels, tags)
 * from all floors and saves it into src/data/searchIndex.js.
 * This file is loaded at startup to support search and chatbot functionality,
 * while heavy coordinate files are dynamically loaded only when navigating to a floor.
 *
 * Run with: node src/scripts/generate_search_index.js
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

// We import all static floors exactly as in floorsData.js
import { basement }  from '../data/apj-block/basement.js'
import { ground }    from '../data/apj-block/ground.js'
import { first }     from '../data/apj-block/first.js'
import { second }    from '../data/apj-block/second.js'
import { third }     from '../data/apj-block/third.js'
import { fourth }    from '../data/apj-block/fourth.js'
import { fifth }     from '../data/apj-block/fifth.js'

import { basement as cv_raman_basement } from '../data/cv-raman-block/basement.js'
import { ground as cv_raman_ground } from '../data/cv-raman-block/ground.js'
import { first as cv_raman_first } from '../data/cv-raman-block/first.js'
import { second as cv_raman_second } from '../data/cv-raman-block/second.js'
import { third as cv_raman_third } from '../data/cv-raman-block/third.js'
import { fourth as cv_raman_fourth } from '../data/cv-raman-block/fourth.js'
import { fifth as cv_raman_fifth } from '../data/cv-raman-block/fifth.js'

import * as ramanujan from '../data/ramanujan-block/floors.js'
import * as smv from '../data/smv-block/floors.js'
import * as atal from '../data/atal-block/floors.js'
import * as rajraman from '../data/rajraman-block/floors.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const floorsData = {
  // APJ Block
  basement,
  ground,
  first,
  second,
  third,
  fourth,
  fifth,

  // CV-Raman Block
  cv_raman_basement,
  cv_raman_ground,
  cv_raman_first,
  cv_raman_second,
  cv_raman_third,
  cv_raman_fourth,
  cv_raman_fifth,

  // Ramanujan Block
  ramanujan_ground: ramanujan.ground,
  ramanujan_first: ramanujan.first,
  ramanujan_second: ramanujan.second,
  ramanujan_third: ramanujan.third,
  ramanujan_fourth: ramanujan.fourth,

  // SMV Block
  smv_ground: smv.ground,
  smv_first: smv.first,
  smv_second: smv.second,
  smv_third: smv.third,
  smv_fourth: smv.fourth,
  smv_fifth: smv.fifth,
  smv_sixth: smv.sixth,

  // Atal Block
  atal_ground: atal.ground,
  atal_first: atal.first,
  atal_second: atal.second,
  atal_third: atal.third,

  // Rajraman Block
  rajraman_ground: rajraman.ground,
  rajraman_first: rajraman.first,
  rajraman_second: rajraman.second,
  rajraman_third: rajraman.third,
}

const cleanSearchIndex = {}

for (const [floorKey, floor] of Object.entries(floorsData)) {
  if (!floor) continue

  // Extract only search-relevant fields
  cleanSearchIndex[floorKey] = {
    buildingName: floor.buildingName || '',
    label: floor.label || '',
    // Filter rooms to exclude SVG positioning/dimensions
    rooms: (floor.rooms || []).map(r => ({
      id: r.id,
      name: r.name,
      type: r.type || 'room',
      faculty: r.faculty || null,
      image: r.image || null,
      tags: r.tags || [],
      department: r.department || '',
      directions: r.directions || '',
      description: r.description || '',
      linkToFloor: r.linkToFloor || null
    })),
    // Keep faculty list
    faculty: (floor.faculty || []).map(f => ({
      name: f.name,
      roomId: f.roomId,
      image: f.image || null,
      description: f.description || '',
      department: f.department || '',
      designation: f.designation || ''
    }))
  }
}

const outputPath = path.join(__dirname, '../data/searchIndex.js')
const fileContent = `/**
 * AUTO-GENERATED SEARCH INDEX
 *
 * Generated by src/scripts/generate_search_index.js.
 * Contains only lightweight metadata required for the search engine and AI chatbot.
 * Excludes heavy SVG coordinate mapping data, which is loaded dynamically.
 */

export const searchIndex = ${JSON.stringify(cleanSearchIndex, null, 2)};
`

fs.writeFileSync(outputPath, fileContent, 'utf8')
console.log(`Successfully generated search index at: ${outputPath}`)
